title: Default file

columns:
  - width: 2/3
    fields:
      alt:
        type: text
      caption:
        type: textarea
  - width: 1/3
    fields: 
      layout:
        type: select
        options:
          one_of_three: 1/3
          two_of_three: 2/3
          one_of_two: 1/2
          one_of_one: 1/1

  