title: Timeline


num: date desc

tabs:
  events:
    label: Évènements
    sections:
      drafts:
        headline: Brouillons
        parent: site.find("chronologie")
        type: pages
        templates: 
          - event
          - link
        status: drafts
        sortBy: year asc
      listed:
        headline: Évènements
        type: pagetable
        limit: 25
        parent: site.find("chronologie")
        templates: 
          - event
          - link
        status: listed
        sortBy: year asc
        info: "{{page.year}} – {{page.theme.fromAutoID.title}}"
        columns:
          title:
            label: Titre
            text: '{{ page.title }}'
            type: text
            width: 1/3
            searchable: true
          year:
            label: Année
            text: '{{ page.year }}'
            type: text
            width: 1/3
            searchable: true
          theme:
            label: Thème
            text: '{{ page.theme.fromAutoID.title }}'
            type: text
            width: 1/3
            searchable: true
      
    
  years:
    label: Années
    sections:
      years:
        headline: Années
        type: pages
        parent: site.find("annees")
        templates: 
          - year
        status: all
  data:
    label: Infos
    sections:
      themes:
        headline: Thèmes
        type: pages
        parent: site.find("themes")
        templates: 
          - theme
        status: all
      data:
        type: fields
        fields:
          tagline:
            label: Sous-titre du site
            type: markdown
          introduction:
            label: Introduction
            type: markdown